version: "3.8"

services:
  auth-service:
    build:
      context: .
    ports:
      - "8000:8000"
    env_file:
      - .env.dev
    depends_on:
      - db
    command: flask run --host=0.0.0.0 --port=8000

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: auth_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
